### ISSUE TITLE
"500: programmer error" (for one resource only)

### ISSUE THREAD

**Issue by bacor** [CANTUS-Project/api#21]
I've been collecting the full CANTUS database through the API and ran into a 500 server error for the following request.

```http
GET /browse HTTP/1.1
Host: abbot.uwaterloo.ca:8888
X-Cantus-Per-Page: 100
X-Cantus-Page: 4637
```

I then narrowed it down to one specific resource:

```http
GET /browse HTTP/1.1
Host: abbot.uwaterloo.ca:8888
X-Cantus-Per-Page: 1
X-Cantus-Page: 463662
```

But note that page number on which I got the error was different on the previous day: then I got the error with `X-Cantus-Page: 463685`. In any case, the response headers for the above request were

```http
Content-Length: 21
Content-Type: text/html; charset=UTF-8
Date: Fri, 05 Oct 2018 10:18:44 GMT
Server: Abbot/0.7.11
X-Cantus-Version: Cantus/0.3.0
```

This seems a minor issue, since out of all 482115 promised by the API, it returned this error for one resource only.

**Comment by crantila** [comment]
Thanks for reporting this @bacor! Since it says "programmer error" and I'm the programmer, I guess it would be hard for me to claim it's not my fault :laughing: 

Because this is a problem with the _implementation_ of the API, rather than a problem in the API (documentation) itself, I've copied your report into a new issue at CANTUS-Project/abbot#118. Over there it will be easier to find in the future&mdash;whenever someone has time to work on the server. But I'm so glad you find this service useful, and I really appreciate your detailed report!

In case you were wondering. The page that triggers an error will definitely change sometimes. That's because the order of items at the `/browse` endpoint is more or less random. (If you want to "choose a random chant" then the order is not random enough for that, but does it change according to factors that are very difficult to track down and explain).

Thank you again, and I welcome additional comments you may have!
